### ISSUE TITLE
Issue: Cannot save settings (and more)

### ISSUE THREAD

**Issue by FredG89** [SpaceK33z/web-to-plex#138] opened 2019-12-22 00:53 UTC
1. Save button does not work and the "skip" option on the managers does not allow toggle. In both Chrome and Firefox developer versions when using the downloadable add-ons.

2. Whenever I open another page or navigate in another tab, the browser jumps back to the plugin page.

3. ~~The Chrome and Firefox store versions are the old versions that does not allow anything but Radarr and Couchpotato.~~

**Comment by Ephellon** [comment] 2019-12-22 15:30
Version numbers please

**Comment by Ephellon** [comment] 2019-12-22 15:35
1. That issue was resolved in update 4.1.1.4 (and under watch) - not experiencing same problem

2. Elaborate please

3. That;s explained in the README and WIki

**Comment by FredG89** [comment] 2019-12-22 16:20
Here are the errors.
https://imgur.com/4SmNmW0
https://imgur.com/BQtxSwq
https://imgur.com/6sBqyiU

1. Chrome Version 79.0.3945.88, Firefox Verison 72.0b9. It shows a stop sign like image when hovering over the toggle. I've tried to take a snapshot of this, but none of my tools are picking up the mouse
https://imgur.com/v9AVShh
https://imgur.com/TQmFthV

2. If I have the Web-to-Plex extension installed. If I open a tab then go to a website, the browser opens another tab to the Web-to-Plex settings. If I click on a link inside a website, the browser either opens another tab to Web-to-Plex or it jumps back to the Web-to-Plex tab that's already open.

**Comment by Ephellon** [comment] 2019-12-22 17:09
The settings haven't been saved. The stop sign means the option is unavailable, you must test the settings (and pass) first

**Comment by Ephellon** [comment] 2019-12-22 17:10
You **must** fill in the settings first... The extension won't use empty settings

**Comment by Ephellon** [comment] 2019-12-22 17:10
The tab is trying to get you to fill out the settings

**Comment by Ephellon** [comment] 2019-12-22 17:11
On mobile, will reorient comments later

**Comment by Ephellon** [comment] 2019-12-22 17:17
I'll rewrite the Wiki and/or setup instructions, but: settings must be tested before they are enabled (they are enabled automatically after testing is successful). The settings will nag you until you press the save button.

**Comment by FredG89** [comment] 2019-12-22 17:51
![1](https://user-images.githubusercontent.com/6701948/71325362-5f020280-24b1-11ea-8451-e08a873751ea.png)
![2](https://user-images.githubusercontent.com/6701948/71325363-5f020280-24b1-11ea-9d1e-f95a9126f55c.png)
![3](https://user-images.githubusercontent.com/6701948/71325364-5f020280-24b1-11ea-8e0f-fc94149e278a.png)
![4](https://user-images.githubusercontent.com/6701948/71325365-5f020280-24b1-11ea-98c3-9a0c8a786c09.png)

**Comment by Ephellon** [comment] 2019-12-22 17:57
Press "test" now

**Comment by FredG89** [comment] 2019-12-22 17:58
I did. It just reloads the Sonarr Storage Path and Quality Profile.

**Comment by Ephellon** [comment] 2019-12-22 19:55
Yes. Now the "skip" button should work as intended. After you're done changing the settings, press "save"

**Comment by FredG89** [comment] 2019-12-22 20:12
Still does not work and save does not work.

**Comment by FredG89** [comment] 2019-12-22 20:14
If you would like, we can do a screen share session or I can take a video.

**Comment by Ephellon** [comment] 2019-12-22 20:23
What's the extension version? Bottom right

**Comment by FredG89** [comment] 2019-12-22 20:25
Version 4.1.0.22

**Comment by Ephellon** [comment] 2019-12-22 20:26
Update to `4.1.1.6` (most recent)

**Comment by Ephellon** [comment] 2019-12-22 20:28
Duplicate of #127

**Comment by FredG89** [comment] 2019-12-22 20:33
How exactly am I going to update? The links on the installation guide page are the current verison that I have installed. The extension webstores are still v3.4.

**Comment by Ephellon** [comment] 2019-12-22 20:41
On the WIki (just changed), download the BETA ZIP version

**Comment by Ephellon** [comment] 2019-12-22 20:44
The packages weren't updated in the last PR. Re-pulling now...

**Comment by FredG89** [comment] 2019-12-28 04:38
So the application seems to save now but does not save the libraries and quality settings. Thus when I try to add something to download, it doesn't do anything. Is there something I can do to try and narrow down what's causing that?

**Comment by FredG89** [comment] 2019-12-28 21:49
Disregard. It seems to work on most sites, just wasn't working on metacritic.com

**Comment by Ephellon** [comment] 2019-12-29 09:08
Hi, just got your message. I'm not sure what you meant by your first comment:

> So the application...

Did you mean:

> "Does not save (quality) settings when trying to download"

**Comment by Ephellon** [comment] 2019-12-29 15:40
Tested on metacritic, nothing out of the ordinary... probably just didn't load fully (metacritic is network intensive)

**Comment by Ephellon** [comment] 2020-01-04 04:04
Nothing posted for a few days, closing.

**Comment by FredG89** [comment] 2020-01-04 04:09
Ah sorry about that. It doesn't really work on Metacritic for me (doesn't parse the movie/show). On IMDB and Movieo it's gone from "Add" to "Modify" even if the show/movie is not in Radarr or Sonarr. Thanks for all your help. Any update when it will be added to the Chrome and Firefox stores?

**Comment by Ephellon** [comment] 2020-01-04 04:10
Yes. Just updated. Send me some examples please

**Comment by Ephellon** [comment] 2020-01-04 04:23
Also, it's designed to go to "Modify [this item]" after engaging the button. You don't have to actually add the item

**Comment by Ephellon** [comment] 2020-01-04 04:24
**Note:` v3.4` has to be updated by hand (by installing a different extension).** The links can be found on the [README](https://SpaceK33z/web-to-plex/)

**Comment by FredG89** [comment] 2020-01-04 07:36
> Also, it's designed to go to "Modify [this item]" after engaging the button. You don't have to actually add the item

So how do I add an item? Does it auto add?

**Comment by FredG89** [comment] 2020-01-04 08:20
![2020-01-04_2-19-12](https://user-images.githubusercontent.com/6701948/71762725-c6985480-2e98-11ea-9398-43bf1be245c7.png)
![2020-01-04_2-19-27](https://user-images.githubusercontent.com/6701948/71762726-c6985480-2e98-11ea-92b7-503f526e9316.png)

**Comment by Ephellon** [comment] 2020-01-04 15:35
Click the button to add. It can only look at 100 items (250 with compression enabled) from each manager.

**Comment by Ephellon** [comment] 2020-01-04 15:35
In your case, it seems to be outside the range of items it added

**Comment by Ephellon** [comment] 2020-01-04 15:36
I'm not sure how to fix this, other than constantly asking the manger for every item every time a page loads

**Comment by Ephellon** [comment] 2020-01-04 15:51
But, I could make an option to always check instead of caching

**Comment by Ephellon** [comment] 2020-01-04 15:54
Hmm, with that, I could also bring back individual buttons (maybe?)

**Comment by Ephellon** [comment] 2020-01-04 15:55
I'm going to go make a mock up, maybe have a testable version out tomorrow

**Comment by Ephellon** [comment] 2020-01-04 16:13
Also, Metacritic is garbage, I can't even open the Plex URLs until it finishes loading... Will fix later

> 7.3s for the page to load the DOM, 1m for it to finish loading the content
![image](https://user-images.githubusercontent.com/8632548/71768298-2eb75c80-2ed2-11ea-9298-e862961d6f60.png)

**Comment by Ephellon** [comment] 2020-01-04 18:42
> Added the `ID Caching Mode` option

![image](https://user-images.githubusercontent.com/8632548/71770205-3e8d6b80-2ee7-11ea-80ec-61d204eb3d0b.png)

**Comment by Ephellon** [comment] 2020-01-04 19:16
Will rename to something less confusing later

**Comment by Ephellon** [comment] 2020-01-12 18:31
> Added the **ID Fetching Mode** setting
![image](https://user-images.githubusercontent.com/8632548/72223700-1b8a3980-352f-11ea-96a7-efcc9041e5a2.png)

**Closed by Ephellon** 2020-01-12 18:31 UTC
Labels: bug, discussion, duplicate, enhancement, help-wanted, wiki
