### ISSUE TITLE
PLEX ERROR

### ISSUE THREAD

**Issue by TCarneiro91** [SpaceK33z/web-to-plex#22] opened 2016-12-28 21:23 UTC
Well, i did everything correctly, even got my x-token (the permanent token) and this is odd.

I did found a bunch of servers on my list, some are from friends of mine. So far so good. But when i choose my server, on imdb and trakt it gives "PLEX ERROR" but if i select other server than mine, it gives the correct information...

My Server is in my LAN but is not my localhost, i don't know if there's a difference about that

**Comment by TCarneiro91** [comment] 2016-12-28 23:21
Yes, it's available (just checked) and i can watch anywhere i am since i have a internet connection, through Browser, Android, etc

If i select a remote server, the extension works fine

![9707e56234a7667e8ee1ce80d40420f4](https://cloud.githubusercontent.com/assets/17798233/21533617/53739eae-cd54-11e6-8374-d5893d0c89de.png)

**Comment by SpaceK33z** [comment] 2016-12-28 23:30
Ah yes, I checked and it seems that a connection without SSL does not work.

Why would you disable SSL though? Not judging you here, just curious to a use-case.

**Comment by TCarneiro91** [comment] 2016-12-28 23:40
I know, once i had some trouble trying to play some stuff in my cellphone, and that did the trick.

Anyway

Still nothing, i've activated the SSL
- Rebooted PMS
- Removed extension and add it again
- Got the token again
- My Server appears, but it's all the same...
- If i change to other person server, it's good

![d7086429821b479d0cb3aad2b367b2ed](https://cloud.githubusercontent.com/assets/17798233/21533851/e9a6aeaa-cd56-11e6-8ee7-8e6d914081d6.png)
![72af0eea05aa37f10208a4060276489d](https://cloud.githubusercontent.com/assets/17798233/21533858/ee65b774-cd56-11e6-96bd-a5f9d589101b.png)
![442e333815debd618e2c4971787df7a4](https://cloud.githubusercontent.com/assets/17798233/21533861/f7a80ed6-cd56-11e6-80ac-1596dd461272.png)
![e839cf648a91575b717560817680218c](https://cloud.githubusercontent.com/assets/17798233/21533863/fb0e1282-cd56-11e6-819e-d44da75bf4d2.png)

**Comment by SpaceK33z** [comment] 2016-12-28 23:48
If you open the Developer Tools (F12) on a movie page on IMDb, what do you see there? You should see a message in the Console `Request to Plex failed, [reason]`.

**Comment by TCarneiro91** [comment] 2016-12-28 23:55
It gives me connection refused, i deactivated firewall and antivirus to see if it was blocking, and they're fine

![9a64ef6aa5403230f05025298d928fc1](https://cloud.githubusercontent.com/assets/17798233/21534034/245634ba-cd59-11e6-9e3a-db36976abefd.jpg)

**Comment by SpaceK33z** [comment] 2016-12-28 23:58
Interesting. If you go to that URL manually, what happens? Also, do you have the latest Plex server version? If not, could you make sure you have that?

**Comment by TCarneiro91** [comment] 2016-12-29 00:01
if i enter that link, it gives no results. Somehow is trying to enter my PMS server through my External IP.

My version is 1.2.7.2987
If this is a trouble i will update it tomorrow

**Comment by SpaceK33z** [comment] 2016-12-29 00:09
I'm on mobile now and dont know the exact Plex versions, but I think that might be the issue. They changed their API in the last version, and the extension only supports the new API. If that was it, I'll add a better warning about that soon.

**Comment by TCarneiro91** [comment] 2016-12-29 22:02
It's not that, updated to latest version, still gives the same error...

![32005fa919be9a043d5e5a49090d40be](https://cloud.githubusercontent.com/assets/17798233/21555708/6f2b1e9c-ce12-11e6-87d9-e9ca33586649.png)

**Comment by SpaceK33z** [comment] 2017-01-02 11:00
I'm sorry, I can understand your frustration with this. It's hard for me to debug this since I can't reproduce this yet.

So if you go to the Plex settings, you see this?

![screen shot 2017-01-02 at 11 47 38](https://cloud.githubusercontent.com/assets/533616/21587882/60dc2a76-d0e1-11e6-81b5-0e608bc9e75c.png)

**Comment by TCarneiro91** [comment] 2017-01-02 22:03
Yes, sure...

I removed all my friend's servers, and there's only mine in the extension list now...
Still the same...

![5489a27f2fcf48bf9792380f52fe699e](https://cloud.githubusercontent.com/assets/17798233/21596736/309cc3c4-d137-11e6-9a44-161432434232.png)

**Comment by h3artbl33d** [comment] 2017-01-06 11:39
If I remember it correctly, if you change the _secure connections_ settings, PMS should be restarted to take that into effect. But since you've upgraded PMS afterwards, that is already done.

So the reason should be sought elsewhere. What other browser plugins are you using? And also relevant, which security suite (AV/firewall) are you using? Some security suites have 'SSL/TLS proxy' in order to sniff the traffic flowing to and from your computer - theoretically, that can cause issues as well.

**Comment by Co85** [comment] 2017-02-21 12:35
I have the same issue and i noticed that the URL is pointing to my external IP adres and port number, but as long as I'm on my local network i cant access my external IP since my router doesnt have any NAT loopback .

So i actually tried and when i get off the local network everything works like a charm but as long as im on the network it doesnt work.

Maybe it would be possible to set a server IP adress manually?

**Comment by skath** [comment] 2017-08-17 03:57
Same problem here. All the extension's HTTP(S) requests are pointed at the plex.direct hostname that resolves to my router's external IP, which won't work while I'm on the same network. 

It's hard to believe this extension isn't designed to work for people who have a plex server on their home network. Is there some kind of workaround?

**Comment by rogueosb** [comment] 2018-03-14 23:42
I also had this error, and fixed it by removing my custom domain under "Custom server access URLs" in my Plex server Network settings (make sure to show advanced settings). I think it may be a certificate mismatch issue between the custom domain and the certs Plex autogenerates.

**Comment by andrewrmoore** [comment] 2018-03-15 17:04
@rogueosb you're right, this fixed it for me.

When using a custom domain in Plex network settings Web to Plex was throwing the following error in the console:

> Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID

The cert is fine (Let's Encrypt).

**Comment by romanar** [comment] 2018-03-15 19:22
Having the same issue.
Settings:
![screen shot 2018-03-15 at 3 21 59 pm](https://user-images.githubusercontent.com/32021606/37486370-ad6e2f52-2864-11e8-81c9-d353b0cb25b3.png)

**Comment by SpaceK33z** [comment] 2018-03-15 21:21
Thanks for your bug reports. I have two solutions that will fix this once and for all, I hope.

- For each server Plex returns a list of possible connections (e.g. one that only works on your LAN, one for remote). Instead of always selecting the remote one, it should work like Plex Web does; try each one till a connection is made.
- Plex servers that are seved as HTTP-only will fail on HTTPS movie sites. To fix this I will need to do the request in a background page.

**Comment by SpaceK33z** [comment] 2018-03-18 11:48
> Plex servers that are served as HTTP-only will fail on HTTPS movie sites. To fix this I will need to do the request in a background page.

This has been fixed now! v3.2 was just released with this fix, it may take some hours before your browser auto-updates.

**Comment by romanar** [comment] 2018-03-19 02:34
Still getting Plex Error. Running Web to Plex 3.2

**Comment by SpaceK33z** [comment] 2018-03-19 09:52
Okay, in that case the next improvement (trying every Plex connection URL) will fix your issue. I guess I'll work on that this week.

**Comment by maxcore** [comment] 2018-03-19 12:22
Thx space 😃

**Comment by SpaceK33z** [comment] 2018-03-20 16:10
I think I've finally nailed this issue, but it is hard to test for me since it has always worked for me. So please try v3.3. It may take some hours before your browser is updated.

Do note that you need to go to the options and hit "Save" again for the fix to have effect.

Please let me know if there are still issues!

**Closed by SpaceK33z** 2018-03-20 16:10 UTC
Labels: bug

**Comment by GugZi** [comment] 2018-03-20 16:13
yea it works

**Comment by romanar** [comment] 2018-03-21 02:05
@SpaceK33z Working for me 2. Thanks
